- name: visxai
  role: program committee
  years:
    - 2021
- name: visxai
  role: organizer
  years:
    - 2022
    - 2023
    - 2024
    - 2025
- name: neurips
  role: reviewer
  years:
    - 2021
    - 2022
    - 2024
- name: icml
  role: reviewer
  years: 
    - 2022
    - 2023
    - 2024
- name: chi
  role: reviewer
  years: 
    - 2022
    - 2024
    - 2025
    - 2026
- name: vis
  role: reviewer
  years:
    - 2024
    - 2025
- name: acm
  role: member
- name: ieee
  role: member
- name: vis
  role: student volunteer
  years:
    - 2024
- name: cvpr
  role: reviewer
  years:
    - 2025
- name: tvcg
  role: reviewer
  years:
    - 2025
- name: uist
  role: reviewer
  years:
    - 2025